# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23a270370243554fd6b11dba332812b738fe49b7705a1547bb876e3a3980fd88f03abb5a4bc1591787cbddf3018fd1e9b2184010ad59090a1afc7d0d893db075

test:
  secret_key_base: df7b1a41f5358e9445b15afcf6b4347d9f33349eb02767c326041e1f0167094667fe511f5e0e94397023043f64a54b4276f5e9be485750563887dbd89b893ccc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
